apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-envoy                    
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Viki2608/python-app.git'
    targetRevision: envoy  # The branch name
    path: gitops                   # The directory inside that branch
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy                    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true